Algoritmo "nadadores"
// Autor(a)    : Tiago Gomes
// Data atual  : 28/09/2017
Var
idade : inteiro
Inicio
Escreva("qual a idade")
leia(idade)
Escolha(idade)
caso 0 ate 4
escreva("Não há escalão")
caso 5 ate 7
escreva ("infantil A")
caso 8 ate 10
escreva ("infantil B")
caso 11 ate 13
escreva("Juvenil A")
caso 14 ate 17
escreva("Juvenil B")
caso 18 ate 111
escreva("senior")
fimescolha
Fimalgoritmo